version: '3'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: my_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - wpsite

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
          - wpsite
volumes:
  db-data:
networks:
  wpsite: